### ISSUE TITLE
Electron app doesn't build on Ubuntu 18.10

### ISSUE THREAD

**Issue by BNolet** [alicerunsonfedora/hyperspace#18]
```  • electron-builder version=20.38.5
  • loaded configuration file=package.json ("build" field)
  • loaded parent configuration preset=react-cra
  • writing effective config file=dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=4.0.4 appOutDir=dist/mac
  • packaging       platform=mas arch=x64 electron=4.0.4 appOutDir=dist/mas
  • downloading               parts=8 size=54 MB url=https://github.com/electron/electron/releases/download/v4.0.4/electron-v4.0.4-mas-x64.zip
  • skipped macOS application code signing reason=supported only on macOS
  • building        target=DMG arch=x64 file=dist/Hyperspace-0.3.0.dmg
  • downloaded                duration=13.382s url=https://github.com/electron/electron/releases/download/v4.0.4/electron-v4.0.4-mas-x64.zip
  • skipped macOS application code signing reason=supported only on macOS
  • rebuilding native production dependencies platform=linux arch=x64
  • packaging       platform=linux arch=x64 electron=4.0.4 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/Hyperspace 0.3.0.AppImage
  • downloading               parts=1 size=1.5 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-9.1.0/appimage-9.1.0.7z
  • downloaded                duration=1.033s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-9.1.0/appimage-9.1.0.7z
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=4.0.4 appOutDir=dist/win-unpacked
  • downloading               parts=8 size=61 MB url=https://github.com/electron/electron/releases/download/v4.0.4/electron-v4.0.4-win32-x64.zip
  • building        target=deb arch=x64 file=dist/hyperspace_0.3.0_amd64.deb
  • downloaded                duration=14.947s url=https://github.com/electron/electron/releases/download/v4.0.4/electron-v4.0.4-win32-x64.zip
  • downloading               parts=1 size=5.0 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z
  • downloaded                duration=17.195s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z
  • downloading               parts=1 size=5.6 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z
  • downloaded                duration=1.992s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z
  ⨯ wine is required, please see https://electron.build/multi-platform-build#linux

Error: /home/brandon/Projects/hyperspace/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/brandon/Projects/hyperspace/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.signAndEditResources (/home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (/home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/winPackager.ts:363:21)
    at go$readdir$cb (/home/brandon/Projects/hyperspace/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at /home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/winPackager.ts:355:73)
    at /home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/platformPackager.ts:250:16
From previous event:
    at WinPackager.doPack (/home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.doBuild (/home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/brandon/Projects/hyperspace/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/brandon/Projects/hyperspace/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/brandon/Projects/hyperspace/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/brandon/Projects/hyperspace/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/brandon/Projects/hyperspace/node_modules/electron-builder/src/cli/cli.ts:46:19)
a405803d6771e0484ac097e2e6ca930a35990f23aeee6cb55640aaecd349f10f  • building        target=rpm arch=x64 file=dist/hyperspace-0.3.0.x86_64.rpm
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hyperspace@0.3.0 build-electron: `npm run purge-dirs; npm run build; build -mwl`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hyperspace@0.3.0 build-electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/brandon/.npm/_logs/2019-02-10T21_11_55_114Z-debug.log
```

Seems like it's trying to build for a Windows target? Why would wine be needed?

**Comment by alicerunsonfedora** [comment]
The `build-electron` command targets all three platforms. I'll add an update to package.json to specify specific platforms.

**Comment by BNolet** [comment]
Unfortunately, because the scripts are trying to build multiple packages (rpm, deb and AppImage) the build phase still fails. 

In particular for my platform the rpm stage fails (make sense, considering I'm on a debian-based platform)

**Comment by alicerunsonfedora** [comment]
RPM still fails for me, too, considering I'm on a Mac. Regardless, I still manage to get the DEB files and AppImage. I might temporarily remove RPM for now.
